## Pandas Series

A Series is a 1-dimensional labeled array capable of holding any data type. The axis labels are collectively called the index.

### Creating Series
There are multiple ways to create a Pandas Series

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
labels = ['a', 'b', 'c']
my_list = [10, 20, 30]
arr = np.array([40, 50, 60])
dictionary = { 'd': 11, 'e': 22, 'f': 33 }

In [ ]:
pd.Series(my_list) # Indexes will be the numbers starting with 0

0    10
1    20
2    30
dtype: int64

In [ ]:
pd.Series(my_list, index = labels) # Set indices/labels/keys instead of 0,1,2,... etc

a    10
b    20
c    30
dtype: int64

In [ ]:
pd.Series(arr) # 1-D Array is fine but 2-D array will throw error because Series itself is 1D

0    40
1    50
2    60
dtype: int64

In [ ]:
pd.Series(dictionary) # Dictionary will have labels/index/keys as keys and value will be the value

d    11
e    22
f    33
dtype: int64