# Pandas DataFrame

A **DataFrame** in Pandas is a two-dimensional, tabular data structure organized into rows and columns, similar to an Excel spreadsheet or a SQL table.

Each column can contain a different data type, such as integers, strings, floats, or dates.

### Key Components
- **Rows:** Represent individual records.
- **Columns:** Represent attributes or features.
- **Index:** Labels used to identify rows (default: `0, 1, 2, ...`).
- **Column Names:** Labels used to identify each column.

### Example

```python
import pandas as pd

data = {
    "Name": ["Alice", "Bob", "Charlie"],
    "Age": [25, 30, 28],
    "City": ["Delhi", "Mumbai", "Noida"]
}

df = pd.DataFrame(data)
print(df)
```

**Output:**
```text
      Name  Age    City
0    Alice   25   Delhi
1      Bob   30  Mumbai
2  Charlie   28   Noida
```

### Common Operations

- `df.head()` — View the first 5 rows.
- `df.shape` — Get the number of rows and columns.
- `df["Name"]` — Select a column.
- `df.iloc[0]` — Select the first row by position.
- `df["Age"].mean()` — Calculate the average age.

**In short:** A DataFrame is a labeled, two-dimensional data structure used to store, manipulate, filter, and analyze structured data in Python.

**1. Creating a DataFrame**

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
data = {
    "Name": ["Alice", "Bob", "Charlie"],
    "Age": [25, 30, 28],
    "City": ["Delhi", "Mumbai", "Noida"],
    "Salary": [10000, 233000, 2828222]
}

df = pd.DataFrame(data)
df

      Name  Age    City   Salary
0    Alice   25   Delhi    10000
1      Bob   30  Mumbai   233000
2  Charlie   28   Noida  2828222

In [ ]:
data = [
    {"Name": "Alice", "Age": 25, "City": "Delhi", "Salary": 50000},
    {"Name": "Bob", "Age": 30, "City": "Mumbai", "Salary": 65000},
    {"Name": "Charlie", "Age": 28, "City": "Noida", "Salary": 55000},
    {"Name": "David", "Age": 35, "City": "Bangalore", "Salary": 80000}
]

In [ ]:
df2 = pd.DataFrame(data)
df2

      Name  Age       City  Salary
0    Alice   25      Delhi   50000
1      Bob   30     Mumbai   65000
2  Charlie   28      Noida   55000
3    David   35  Bangalore   80000

In [ ]:
data = [
    ["Alice", 25, "Delhi", 50000],
    ["Bob", 30, "Mumbai", 65000],
    ["Charlie", 28, "Noida", 55000],
    ["David", 35, "Bangalore", 80000],
    ["Emma", 24, "Delhi", 45000],
    ["Frank", 32, "Mumbai", 70000]
]

df_list_of_list_default_labels = pd.DataFrame(data)
df_list_of_list_default_labels

         0   1          2      3
0    Alice  25      Delhi  50000
1      Bob  30     Mumbai  65000
2  Charlie  28      Noida  55000
3    David  35  Bangalore  80000
4     Emma  24      Delhi  45000
5    Frank  32     Mumbai  70000

In [ ]:
df_list_of_list_with_labels = pd.DataFrame(data, columns=["Name", "Age", "City", "Salary"])
df_list_of_list_with_labels

      Name  Age       City  Salary
0    Alice   25      Delhi   50000
1      Bob   30     Mumbai   65000
2  Charlie   28      Noida   55000
3    David   35  Bangalore   80000
4     Emma   24      Delhi   45000
5    Frank   32     Mumbai   70000

**2. Selection and indexing of columns**

In [ ]:
df_list_of_list_with_labels['Name']

0      Alice
1        Bob
2    Charlie
3      David
4       Emma
5      Frank
Name: Name, dtype: object

In [ ]:
df_list_of_list_with_labels[["Name", "Salary"]]

      Name  Salary
0    Alice   50000
1      Bob   65000
2  Charlie   55000
3    David   80000
4     Emma   45000
5    Frank   70000

**3. Creating a new column**

In [ ]:
df_list_of_list_with_labels["Designation"] = ["Doctor", "Eng.", "Doctor", "HR", "Eng.", "Teacher"]

In [ ]:
df_list_of_list_with_labels

      Name  Age       City  Salary Designation
0    Alice   25      Delhi   50000      Doctor
1      Bob   30     Mumbai   65000        Eng.
2  Charlie   28      Noida   55000      Doctor
3    David   35  Bangalore   80000          HR
4     Emma   24      Delhi   45000        Eng.
5    Frank   32     Mumbai   70000     Teacher

**4. Removing Columns**

In [ ]:
df_list_of_list_with_labels.drop("Designation", axis = 1)

      Name  Age       City  Salary
0    Alice   25      Delhi   50000
1      Bob   30     Mumbai   65000
2  Charlie   28      Noida   55000
3    David   35  Bangalore   80000
4     Emma   24      Delhi   45000
5    Frank   32     Mumbai   70000

In [ ]:
df_list_of_list_with_labels # Normal Drop won't remove the data by reference, for in-place you need to provide additional argument (see below)

      Name  Age       City  Salary Designation
0    Alice   25      Delhi   50000      Doctor
1      Bob   30     Mumbai   65000        Eng.
2  Charlie   28      Noida   55000      Doctor
3    David   35  Bangalore   80000          HR
4     Emma   24      Delhi   45000        Eng.
5    Frank   32     Mumbai   70000     Teacher

In [ ]:
df_list_of_list_with_labels.drop("Designation", axis = 1, inplace = True)
df_list_of_list_with_labels

      Name  Age       City  Salary
0    Alice   25      Delhi   50000
1      Bob   30     Mumbai   65000
2  Charlie   28      Noida   55000
3    David   35  Bangalore   80000
4     Emma   24      Delhi   45000
5    Frank   32     Mumbai   70000

In [ ]:
# Adding the column back since remove by reference was done earlier using in-place arg
df_list_of_list_with_labels["Designation"] = ["Doctor", "Eng.", "Doctor", "HR", "Eng.", "Teacher"]

In [ ]:
df_list_of_list_with_labels

      Name  Age       City  Salary Designation
0    Alice   25      Delhi   50000      Doctor
1      Bob   30     Mumbai   65000        Eng.
2  Charlie   28      Noida   55000      Doctor
3    David   35  Bangalore   80000          HR
4     Emma   24      Delhi   45000        Eng.
5    Frank   32     Mumbai   70000     Teacher

In [ ]:
df_list_of_list_with_labels.drop(0, axis = 0) # Remove first row now ( Alice will be gone in the returned copy)

      Name  Age       City  Salary Designation
1      Bob   30     Mumbai   65000        Eng.
2  Charlie   28      Noida   55000      Doctor
3    David   35  Bangalore   80000          HR
4     Emma   24      Delhi   45000        Eng.
5    Frank   32     Mumbai   70000     Teacher

**5. Selecting Rows**

In [ ]:
# df_list_of_list_with_labels[0] -> Wrong approach to select a row, it won't work in Data frames

df_list_of_list_with_labels.loc[0]

Name            Alice
Age                25
City            Delhi
Salary          50000
Designation    Doctor
Name: 0, dtype: object

In [ ]:
df_list_of_list_with_labels.loc[[3,4]] # Select mulitiple rows

    Name  Age       City  Salary Designation
3  David   35  Bangalore   80000          HR
4   Emma   24      Delhi   45000        Eng.

In [ ]:
df_list_of_list_with_labels.iloc[0] # Same as "df_list_of_list_with_labels.loc[0]" to some extent

Name            Alice
Age                25
City            Delhi
Salary          50000
Designation    Doctor
Name: 0, dtype: object

**6. Selecting Subsets of Rows and Columns**

In [ ]:
df_list_of_list_with_labels.loc[[3,4]][["Name", "City", "Salary"]] # Select 3 and 4th row in which only select columns Name, City, Salary

    Name       City  Salary
3  David  Bangalore   80000
4   Emma      Delhi   45000

**7. Conditional Selection**

In [ ]:
# Select only those people whose age > 30
df_list_of_list_with_labels[df_list_of_list_with_labels["Age"] > 30]

    Name  Age       City  Salary Designation
3  David   35  Bangalore   80000          HR
5  Frank   32     Mumbai   70000     Teacher

In [ ]:
# Select people age > 30 and they live in city = Mumbai
df_list_of_list_with_labels[(df_list_of_list_with_labels["Age"] > 30) & (df_list_of_list_with_labels["City"] == "Mumbai")]

    Name  Age    City  Salary Designation
5  Frank   32  Mumbai   70000     Teacher