In [34]:
import numpy as np
import pandas as pd

**Finding Missing Data**

In [ ]:
data = {
    "A": ["Alice", np.nan, "Bob", "Charlie", np.nan],
    "B": [12, np.nan, 30, 28, 45],
    "C": [1, 2, 3, np.nan, np.nan],
    "D": [1, np.nan, np.nan, np.nan, 5],
    "E": [6,3,1,3,5]
}

df = pd.DataFrame(data)
df

         A     B    C    D  E
0    Alice  12.0  1.0  1.0  6
1      NaN   NaN  2.0  NaN  3
2      Bob  30.0  3.0  NaN  1
3  Charlie  28.0  NaN  NaN  3
4      NaN  45.0  NaN  5.0  5

In [ ]:
df.isna()

       A      B      C      D      E
0  False  False  False  False  False
1   True   True  False   True  False
2  False  False  False   True  False
3  False  False   True   True  False
4   True  False   True  False  False

In [ ]:
df.isna().sum()

A    2
B    1
C    2
D    3
E    0
dtype: int64

In [ ]:
df.isna().any() # Column having at least one Null value

A     True
B     True
C     True
D     True
E    False
dtype: bool

**Removing Missing Data**

In [ ]:
df.dropna() # All the rows has Null value in it so the result will be empty

       A     B    C    D  E
0  Alice  12.0  1.0  1.0  6

In [ ]:
df

         A     B    C    D  E
0    Alice  12.0  1.0  1.0  6
1      NaN   NaN  2.0  NaN  3
2      Bob  30.0  3.0  NaN  1
3  Charlie  28.0  NaN  NaN  3
4      NaN  45.0  NaN  5.0  5

In [ ]:
df.dropna(thresh=3) # Row at least should have 3-non Null values

         A     B    C    D  E
0    Alice  12.0  1.0  1.0  6
2      Bob  30.0  3.0  NaN  1
3  Charlie  28.0  NaN  NaN  3
4      NaN  45.0  NaN  5.0  5

**Filling the Missing Data**

In [ ]:
df.fillna(0) # Mutation is not in-place ( will have to provider separate inplace argument in the fillna() call)

         A     B    C    D  E
0    Alice  12.0  1.0  1.0  6
1        0   0.0  2.0  0.0  3
2      Bob  30.0  3.0  0.0  1
3  Charlie  28.0  0.0  0.0  3
4        0  45.0  0.0  5.0  5

In [ ]:
default_null_replacement = { 'A': 'John Doe', 'B': 100, 'C': 20, 'D': 400}
df.fillna(value = default_null_replacement)

          A      B     C      D  E
0     Alice   12.0   1.0    1.0  6
1  John Doe  100.0   2.0  400.0  3
2       Bob   30.0   3.0  400.0  1
3   Charlie   28.0  20.0  400.0  3
4  John Doe   45.0  20.0    5.0  5

In [ ]:
df

         A     B    C    D  E
0    Alice  12.0  1.0  1.0  6
1      NaN   NaN  2.0  NaN  3
2      Bob  30.0  3.0  NaN  1
3  Charlie  28.0  NaN  NaN  3
4      NaN  45.0  NaN  5.0  5

In [ ]:
df.fillna(df[["B", "C", "D", "E"]].mean()) # Fill the null values with the "Mean" since column "A" has
                                           # string values so we slice that and then find the mean

         A      B    C    D  E
0    Alice  12.00  1.0  1.0  6
1      NaN  28.75  2.0  3.0  3
2      Bob  30.00  3.0  3.0  1
3  Charlie  28.00  2.0  3.0  3
4      NaN  45.00  2.0  5.0  5