In [ ]:
import numpy as np
import pandas as pd

**Merging 2 dataframes**

In [ ]:
employees = pd.DataFrame({
    "employee_id": [101, 102, 103, 104, 106],
    "name": ["Alice", "Bob", "Charlie", "David", "Emma"],
    "department": ["Engineering", "HR", "Finance", "Engineering", "Marketing"]
})

# DataFrame 2: Salary info
salaries = pd.DataFrame({
    "employee_id": [101, 102, 103, 104, 107],
    "salary": [80000, 60000, 75000, 90000, 65000],
    "bonus": [10000, 5000, 8000, 12000, 6000]
})

In [ ]:
employees

   employee_id     name   department
0          101    Alice  Engineering
1          102      Bob           HR
2          103  Charlie      Finance
3          104    David  Engineering
4          106     Emma    Marketing

In [ ]:
salaries

   employee_id  salary  bonus
0          101   80000  10000
1          102   60000   5000
2          103   75000   8000
3          104   90000  12000
4          107   65000   6000

In [ ]:
pd.merge(employees, salaries) # Merge two Data Frames

   employee_id     name   department  salary  bonus
0          101    Alice  Engineering   80000  10000
1          102      Bob           HR   60000   5000
2          103  Charlie      Finance   75000   8000
3          104    David  Engineering   90000  12000

In [ ]:
pd.merge(employees, salaries, on = "employee_id", how = "inner") # Common ids will be included only and rest will be ignored

   employee_id     name   department  salary  bonus
0          101    Alice  Engineering   80000  10000
1          102      Bob           HR   60000   5000
2          103  Charlie      Finance   75000   8000
3          104    David  Engineering   90000  12000

In [ ]:
pd.merge(employees, salaries, on = "employee_id", how = "outer") # Everything will be included and empty cell will be filled with NaN

   employee_id     name   department   salary    bonus
0          101    Alice  Engineering  80000.0  10000.0
1          102      Bob           HR  60000.0   5000.0
2          103  Charlie      Finance  75000.0   8000.0
3          104    David  Engineering  90000.0  12000.0
4          106     Emma    Marketing      NaN      NaN
5          107      NaN          NaN  65000.0   6000.0

In [ ]:
pd.merge(employees, salaries, on = "employee_id", how = "left") # Data will be merged on the basis of Employees

   employee_id     name   department   salary    bonus
0          101    Alice  Engineering  80000.0  10000.0
1          102      Bob           HR  60000.0   5000.0
2          103  Charlie      Finance  75000.0   8000.0
3          104    David  Engineering  90000.0  12000.0
4          106     Emma    Marketing      NaN      NaN

In [ ]:
pd.merge(employees, salaries, on = "employee_id", how = "right") # Data will be merged on the basis of Salaries

   employee_id     name   department  salary  bonus
0          101    Alice  Engineering   80000  10000
1          102      Bob           HR   60000   5000
2          103  Charlie      Finance   75000   8000
3          104    David  Engineering   90000  12000
4          107      NaN          NaN   65000   6000

**Concatenation of 2 dataframes**

In [ ]:
dict1 = pd.DataFrame({
    "id": [1, 2, 3, 4, 5],
    "name": ["Alice", "Bob", "Charlie", "David", "Emma"],
    "age": [25, 30, 28, 35, 24]
})

dict2 = pd.DataFrame({
    "id": [6, 7, 8, 9, 10],
    "name": ["Frank", "Grace", "Henry", "Ivy", "Jack"],
    "age": [32, 27, 29, 31, 26]
})

In [ ]:
dict1

   id     name  age
0   1    Alice   25
1   2      Bob   30
2   3  Charlie   28
3   4    David   35
4   5     Emma   24

In [ ]:
dict2

   id   name  age
0   6  Frank   32
1   7  Grace   27
2   8  Henry   29
3   9    Ivy   31
4  10   Jack   26

In [ ]:
pd.concat([dict1, dict2]) # Data concatenating on the basis of column

   id     name  age
0   1    Alice   25
1   2      Bob   30
2   3  Charlie   28
3   4    David   35
4   5     Emma   24
0   6    Frank   32
1   7    Grace   27
2   8    Henry   29
3   9      Ivy   31
4  10     Jack   26

In [ ]:
pd.concat([dict1, dict2], axis=1) # Data concatenating on the basis of row

   id     name  age  id   name  age
0   1    Alice   25   6  Frank   32
1   2      Bob   30   7  Grace   27
2   3  Charlie   28   8  Henry   29
3   4    David   35   9    Ivy   31
4   5     Emma   24  10   Jack   26

**Joining 2 Data frames**

In [ ]:
df1 = pd.DataFrame({
    'name': ['Alice', 'Bob', 'Charlie']
}, index=[1,2,3])

df2 = pd.DataFrame({
    'score': [67, 90, 56]
}, index=[2,3,4])

In [ ]:
df1

      name
1    Alice
2      Bob
3  Charlie

In [ ]:
df2

   score
2     67
3     90
4     56

In [ ]:
df1.join(df2)

      name  score
1    Alice    NaN
2      Bob   67.0
3  Charlie   90.0

In [ ]:
df2.join(df1)

   score     name
2     67      Bob
3     90  Charlie
4     56      NaN

In [ ]:
df1.join(df2, how="outer")

      name  score
1    Alice    NaN
2      Bob   67.0
3  Charlie   90.0
4      NaN   56.0

In [ ]:
df2.join(df1, how="outer")

   score     name
1    NaN    Alice
2   67.0      Bob
3   90.0  Charlie
4   56.0      NaN