In [11]:
import numpy as np
import pandas as pd

In [12]:
data = {
    "Order_ID": [1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011, 1012],
    "Order_Date": [
        "2026-01-05", "2026-01-08", "2026-01-12", "2026-01-15",
        "2026-02-02", "2026-02-10", "2026-02-14", "2026-02-20",
        "2026-03-03", "2026-03-09", "2026-03-15", "2026-03-22"
    ],
    "Employee": [
        "Alice", "Bob", "Alice", "Charlie", "Bob", "Alice",
        "Charlie", "Bob", "Alice", "Charlie", "Bob", "Alice"
    ],
    "Department": [
        "Electronics", "Clothing", "Furniture", "Electronics",
        "Clothing", "Furniture", "Electronics", "Clothing",
        "Furniture", "Electronics", "Clothing", "Furniture"
    ],
    "Region": [
        "North", "South", "East", "West", "North", "South",
        "East", "West", "North", "South", "East", "West"
    ],
    "Quantity": [2, 5, 1, 3, 4, 2, 6, 3, 2, 4, 5, 1],
    "Unit_Price": [15000, 800, 12000, 20000, 1000, 10000, 18000, 900, 14000, 22000, 1200, 11000],
    "Payment_Mode": [
        "Card", "Cash", "UPI", "Card", "UPI", "Cash",
        "Card", "UPI", "Cash", "Card", "UPI", "Cash"
    ],
    "Customer_Rating": [4, 5, 3, 4, 5, 4, 2, 3, 5, 4, 3, 5]
}

df = pd.DataFrame(data)
df

,Order_ID,Order_Date,Employee,Department,Region,Quantity,Unit_Price,Payment_Mode,Customer_Rating
0,1001,2026-01-05,Alice,Electronics,North,2,15000,Card,4
1,1002,2026-01-08,Bob,Clothing,South,5,800,Cash,5
2,1003,2026-01-12,Alice,Furniture,East,1,12000,UPI,3
3,1004,2026-01-15,Charlie,Electronics,West,3,20000,Card,4
4,1005,2026-02-02,Bob,Clothing,North,4,1000,UPI,5
5,1006,2026-02-10,Alice,Furniture,South,2,10000,Cash,4
6,1007,2026-02-14,Charlie,Electronics,East,6,18000,Card,2
7,1008,2026-02-20,Bob,Clothing,West,3,900,UPI,3
8,1009,2026-03-03,Alice,Furniture,North,2,14000,Cash,5
9,1010,2026-03-09,Charlie,Electronics,South,4,22000,Card,4
10,1011,2026-03-15,Bob,Clothing,East,5,1200,UPI,3
11,1012,2026-03-22,Alice,Furniture,West,1,11000,Cash,5

In [13]:
df['Month'] = pd.to_datetime(df['Order_Date']).dt.month_name() # Converting to Order_Date values to datetime like because they are strings in the input
df

,Order_ID,Order_Date,Employee,Department,Region,Quantity,Unit_Price,Payment_Mode,Customer_Rating,Month
0,1001,2026-01-05,Alice,Electronics,North,2,15000,Card,4,January
1,1002,2026-01-08,Bob,Clothing,South,5,800,Cash,5,January
2,1003,2026-01-12,Alice,Furniture,East,1,12000,UPI,3,January
3,1004,2026-01-15,Charlie,Electronics,West,3,20000,Card,4,January
4,1005,2026-02-02,Bob,Clothing,North,4,1000,UPI,5,February
5,1006,2026-02-10,Alice,Furniture,South,2,10000,Cash,4,February
6,1007,2026-02-14,Charlie,Electronics,East,6,18000,Card,2,February
7,1008,2026-02-20,Bob,Clothing,West,3,900,UPI,3,February
8,1009,2026-03-03,Alice,Furniture,North,2,14000,Cash,5,March
9,1010,2026-03-09,Charlie,Electronics,South,4,22000,Card,4,March
10,1011,2026-03-15,Bob,Clothing,East,5,1200,UPI,3,March
11,1012,2026-03-22,Alice,Furniture,West,1,11000,Cash,5,March

In [14]:
df['Quarter'] = 'Q' + pd.to_datetime(df['Order_Date']).dt.quarter.astype(str)
df

,Order_ID,Order_Date,Employee,Department,Region,Quantity,Unit_Price,Payment_Mode,Customer_Rating,Month,Quarter
0,1001,2026-01-05,Alice,Electronics,North,2,15000,Card,4,January,Q1
1,1002,2026-01-08,Bob,Clothing,South,5,800,Cash,5,January,Q1
2,1003,2026-01-12,Alice,Furniture,East,1,12000,UPI,3,January,Q1
3,1004,2026-01-15,Charlie,Electronics,West,3,20000,Card,4,January,Q1
4,1005,2026-02-02,Bob,Clothing,North,4,1000,UPI,5,February,Q1
5,1006,2026-02-10,Alice,Furniture,South,2,10000,Cash,4,February,Q1
6,1007,2026-02-14,Charlie,Electronics,East,6,18000,Card,2,February,Q1
7,1008,2026-02-20,Bob,Clothing,West,3,900,UPI,3,February,Q1
8,1009,2026-03-03,Alice,Furniture,North,2,14000,Cash,5,March,Q1
9,1010,2026-03-09,Charlie,Electronics,South,4,22000,Card,4,March,Q1
10,1011,2026-03-15,Bob,Clothing,East,5,1200,UPI,3,March,Q1
11,1012,2026-03-22,Alice,Furniture,West,1,11000,Cash,5,March,Q1

In [15]:
pd.pivot_table(df, values="Unit_Price", index="Region", columns="Department") # Aggregation func Default is "mean"

Department  Clothing  Electronics  Furniture
Region
East          1200.0      18000.0    12000.0
North         1000.0      15000.0    14000.0
South          800.0      22000.0    10000.0
West           900.0      20000.0    11000.0

In [16]:
pd.pivot_table(df, values="Unit_Price", index="Region", columns="Department", aggfunc="median")

Department  Clothing  Electronics  Furniture
Region
East          1200.0      18000.0    12000.0
North         1000.0      15000.0    14000.0
South          800.0      22000.0    10000.0
West           900.0      20000.0    11000.0

In [17]:
pd.pivot_table(df, values=["Unit_Price", "Quantity"], index="Region", columns="Department")

           Quantity                       Unit_Price
Department Clothing Electronics Furniture   Clothing Electronics Furniture
Region
East            5.0         6.0       1.0     1200.0     18000.0   12000.0
North           4.0         2.0       2.0     1000.0     15000.0   14000.0
South           5.0         4.0       2.0      800.0     22000.0   10000.0
West            3.0         3.0       1.0      900.0     20000.0   11000.0

**CROSS TABS**

In [18]:
pd.crosstab(df['Region'], df['Employee'])

Employee  Alice  Bob  Charlie
Region
East          1    1        1
North         2    1        0
South         1    1        1
West          1    1        1